# Generated by Django 5.2.3 on 2025-06-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogInteraccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100)),
                ('mensaje_usuario', models.TextField()),
                ('respuesta_bot', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('canal', models.CharField(default='prueba_web', max_length=50)),
            ],
        ),
    ]
