# Generated by Django 5.2.3 on 2025-06-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_loginteraccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginteraccion',
            name='message_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
